version: '3.9'

services:
  avaazengineeringexercise:
    image: avaazengineeringexercise
    build:
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: v25xhycLlRY3sV7Z
      MYSQL_DATABASE: "exercise"
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 55

  database-dev:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecurePassword
      MYSQL_DATABASE: "exercise"
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - avaaz
    profiles:
      - dev

networks:
  avaaz:
    external: true
